dist: xenial
language: python
cache: pip

python:
  - "3.7"

install:
  - pip install -r requirements-test.txt
  - pip install coveralls

script:
  - coverage run -m pytest

after_success:
  - coveralls

deploy:
  provider: script
  script: bash scripts/deploy_pipy.sh "${PYPI_USER}" "${PYPI_PASS}"
  skip_cleanup: true
  on:
    tags: true
